version: "3.8"
services:
  flask_app:
    build: ./flask/stock_viz_app
    command: gunicorn -b 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=stock_viz
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=postgres_db
      - DB_PORT=5432
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_container_flask
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: stock_viz
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/db_design/stock_viz.sql:/docker-entrypoint-initdb.d/stock_viz.sql

  pgadmin:
    container_name: pgadmin_container_flask
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - postgres_db
